[package]
edition = "2021"
name = "hfml_data_preprocessor"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
float-ord = "0.3.2"
gsl_rust = {version = "*", path = "../gsl_rust"}
#convolve = { version = "*", path = "../convolve" }
bincode = "1.3.3"
permutation = "0.2.5"
#sled = { version = "0.34.7", features = ["compression"] }
fast-float = "0.2.0"
log = "0.4.14"
num-complex = "0.4"
num-traits = "0.2"
once_cell = "1.9.0"
serde = {version = "1.0", features = ["derive"]}
simplelog = "0.11.2"
sysinfo = {version = "0.22.5", default-features = false}
toml = "0.5.8"
rayon = "1.5.1"
