[package]
authors = ["Pim van den Berg"]
edition = "2021"
license-file = "LICENSE"
name = "hfml_data_preprocessor"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
cufft_rust = {version = "*", path = "../cufft_rust"}
clap = {version = "3.0", features = ["derive"]}
fast-float = "0.2.0"
float-ord = "0.3.2"
gsl_rust = {version = "*", path = "../gsl_rust"}
log = "0.4.14"
num-complex = "0.4"
num-traits = "0.2"
rayon = "1.5.1"
serde = {version = "1.0", features = ["derive"]}
simplelog = "0.11.2"
toml = "0.5.8"
ryu = "1.0.9"
#bincode = "1.3.3"
#convolve = { version = "*", path = "../convolve" }
#sled = { version = "0.34.7", features = ["compression"] }

[profile.release]
# Maximum optimization
#codegen-units = 1
lto = "fat"
# Keep debug info
debug = true
# Prefer a panic over UB
overflow-checks = true
