[project]
files = ["13"] # Ranges and raw filenames are allowed
title = "Test"

[rename]
"B(T)" = "B"
Field = "B"
"S1_Vxx_8_13_x" = "Vxx"
"S1_Vxy_9_13_x" = "Vxy"

[extract.Vxx]
x = "B"
y = "Vxx"

[extract.Vxy]
x = "B"
y = "Vxy"

[preprocessing]
interpolation_log2 = 3
invert_x = false
prefactor.x = 1
prefactor.y = 1

[processing]
kind = "fft"

[processing.fft]
center = true
cuda = true
zero_pad_log2 = 10
