[project]
output = ["raw", "intermediate", "final"]
threading = true

[[project.files]]
dest = "measurement_013"
source = "file.013.dat"

[rename]
"B(T)" = "B"
"Field" = "B"
"S1_Vxx_8_13_x" = "Vxx"
"S1_Vxy_9_13_x" = "Vxy"
"V_37_x" = "Vxy"
"V_68_x" = "Vxx"

[extract.Vxx]
x = "B"
y = "Vxx"

[extract.Vxy]
x = "B"
y = "Vxy"

[preprocessing]
invert_x = true
trim_left = 12
trim_right = 32.95

[preprocessing.interpolation]
algorithm = "linear"
n = "min"

[preprocessing.prefactor]
x = 1
y = 1

[processing]
kind = "fft"

[processing.fft]
center = true
cuda = false
hann = true
truncate_lower = 100
truncate_upper = 600
zero_pad = "2^22"
